### ISSUE TITLE
What prevents restricted token holder from using it’s proof token instead ?

### ISSUE THREAD

**Issue by Gozala** [ucan-wg/ucan#17]
I assumed that proofs would be distinguishable from a tokens via extra signature or something so that derived token holder could not simply pull out more capable proof in to escalate privileges. However I can’t see evidence of that in the implementation and spec also seems to suggest that:

> Inline proofs MUST include the entire encoded token, since they will be validated by the receiver.
From: https://whitepaper.fission.codes/access-control/ucan/jwt-authentication

Tests in the repo also seem to suggest the same

https://github.com/ucan-wg/ucan/blob/bfbdbdac3cd7cd58d0382c683d2843a536e1eb9d/tests/token.test.ts#L57-L69

I may be misunderstanding something and if so it is probably a good idea to update language to communicate this more clearly.

**Comment by expede** [comment]
You need to sign a UCAN to the service that you're making a request to. You'd need the root key in order to do that.

**Comment by expede** [comment]
Just flagging that all of this kind of thing (end to end flows, helper functions, &c) needs to end up in the formal spec that will be in this GH org... "soon"

**Comment by expede** [comment]
Thank you for raising it 🙏

**Comment by expede** [comment]
(This got answered above, and confirmed in Discord. TL;DR this needs to be made clearer in prose, and ideally with helpers in the library's API)

**Comment by burdiyan** [comment]
@expede I was just trying to understand how the capability is exercised in the end, and bumped into this issue. Reading the website or the spec it was not immediately clear to me that the client has to issue a separate UCAN to the resource owner to actually exercise the capability.

It seems like there has to be something that would authenticate the caller with the service, is that correct?

Say, a Server issues an admin token to Alice, then Alice gives an attenuated token to Bob. Then when Bob calls the Server, Bob creates a new UCAN as far as I understand, but the Server still needs a way to verify that Bob is actually Bob, right? Or am I missing something?
